### PR TITLE
[MIP-186] Table Timeseries Widget should return data according to the…

### PR DESCRIPTION
**Pull request by sandeshsoni**
… recent date first.

### CODE REVIEW

**Comment by sandeshsoni** [comment]
Hi @BandanaPandey 

In other functions code is written as
`      order_by: ^[desc: dynamic([d], fragment("date_filt"))],`
I can match to do the same.

About other functions mostly have limit: 1 passed.
`  def latest_group_by_date_query(`

Other way, maybe we send a limit 5 or some number and say get latest?

**Review by BandanaPandey — CHANGES_REQUESTED** [review]
@sandeshsoni Please make this change for all the `group_by_date_query` functions present in this file,
currently you have done it only for `max` type aggregator, you need to do the same for all types of aggregator.

**Comment by sandeshsoni** [comment]
@BandanaPandey  I made the changes. Plz review.

Also this function has asc order, I made it desc order.
https://github.com/DataKrewTech/MADS-IoT-Explorer/pull/245/files#diff-5eb0f0d02c398e85029ad9ff01bae88a27a8a61d7247351a74243cfaa2e40467R400

**Review by BandanaPandey — APPROVED** [review]

**Comment by sandeshsoni** [comment]
@chandradot99 How does this branch look to you?

**Pull request merged**
