### PR TITLE
Create cockpit users table

### PR DESCRIPTION
**Pull request by niteshcode4u**

### CODE REVIEW

**Comment by BandanaPandey** [comment]
@niteshcode4u  Please move migration to this PR,
#256
cc @arjun289

**Comment by oyeb** [comment]
Not a direct comment on this PR's content, slightly broader scope:
We know that our old tables have integer PKs along with UUID columns, so should we start switching to UUIDs for new schemas or stick to integers?

**Comment by niteshcode4u** [comment]
> Not a direct comment on this PR's content, slightly broader scope: We know that our old tables have integer PKs along with UUID columns, so should we start switching to UUIDs for new schemas or stick to integers?

For the current PRs, we should go with the flow and maintain consistency i guess

**Comment by BandanaPandey** [comment]
yes @oyeb and @niteshcode4u we do need to switch to uuid instead of id,
So @niteshcode4u  Can we use uuid in place of id for new flow or apis ?

**Comment by niteshcode4u** [comment]
> yes @oyeb and @niteshcode4u we do need to switch to uuid instead of id, So @niteshcode4u Can we use uuid in place of id for new flow or apis ?

Okay, we can do that. So our primary key will UUID, right? Also, I think we should use the same changes for `share_resources` table. @BandanaPandey

**Comment by niteshcode4u** [comment]
@BandanaPandey please have a look

**Comment by niteshcode4u** [comment]
@BandanaPandey I will close this PR and mere it to #256

**Comment by niteshcode4u** [comment]
@BandanaPandey Closing this PR and Will merge it to #256

**Pull request closed without merging**
